# Generated by Django 3.0.5 on 2020-04-02 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256, unique=True)),
                ('Cost', models.PositiveSmallIntegerField()),
                ('Company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order_management.Company')),
            ],
        ),
    ]
