# Generated by Django 3.0.5 on 2020-04-02 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_No', models.CharField(max_length=256)),
                ('Rate', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Total_Price', models.IntegerField()),
                ('Comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Company')),
                ('Product', models.ForeignKey(limit_choices_to={'Company': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Company')}, on_delete=django.db.models.deletion.CASCADE, to='order_management.Product')),
            ],
        ),
    ]
