# Generated by Django 3.0.5 on 2020-04-02 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0003_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Comp',
            new_name='Company',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Product'),
        ),
    ]
