# Generated by Django 3.0.5 on 2020-04-02 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0004_auto_20200403_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='modelp',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='order_management.Product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='order_management.Product'),
        ),
    ]
