# Generated by Django 3.0.5 on 2020-04-02 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0005_auto_20200403_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='modelp',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Rate',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
