# Generated by Django 3.0.5 on 2020-04-02 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0006_auto_20200403_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Total_Price',
            field=models.IntegerField(blank=True),
        ),
    ]
