# Generated by Django 3.0.5 on 2020-04-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0008_auto_20200403_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_management.Company'),
        ),
    ]
